# Generated by Django 4.2.4 on 2023-08-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='dep_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='dep_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
    ]
